import { BALI_PLACES, BALI_SAMPLE, DANANG_PLACES, DANANG_SAMPLE, HAWAII_PLACES, HAWAII_SAMPLE, PARIS_PLACES, PARIS_SAMPLE, TOKYO_PLACES, TOKYO_SAMPLE } from "./data-world.js";
import { icon } from "./icons.js";

/* ============================== 데이터 ============================== */
export const CATS = {
  sight: { label: "명소",      emoji: "🏛️", icon: "landmark", color: "#e8590c" },
  view:  { label: "뷰포인트",  emoji: "🌅", icon: "sunset",   color: "#e67700" },
  nature:{ label: "공원·자연", emoji: "🌿", icon: "trees",    color: "#2f9e44" },
  beach: { label: "해변",      emoji: "🏖️", icon: "waves",    color: "#1c7ed6" },
  food:  { label: "맛집",      emoji: "🍽️", icon: "utensils", color: "#c2255c" },
  cafe:  { label: "카페·브런치",emoji: "☕", icon: "coffee",   color: "#8d5b3e" },
  bar:   { label: "바·루프탑", emoji: "🍸", icon: "martini",  color: "#7048e8" },
  shop:  { label: "쇼핑",      emoji: "🛍️", icon: "bag",      color: "#d6336c" },
  hotel: { label: "숙소",      emoji: "🏨", icon: "bed",      color: "#495057" },
  trans: { label: "교통",      emoji: "⛴️", icon: "tram",     color: "#0b7285" },
  mine:  { label: "내 장소",   emoji: "⭐", icon: "star",     color: "#e03131" },
  stay:  { label: "에어비앤비 후보", emoji: "🏠", icon: "house", color: "#ff385c" },
};

// 좌표는 대략적인 위치입니다. 정확한 위치·영업시간은 구글맵 버튼으로 확인하세요.
export const SYDNEY_PLACES = [
  // 명소
  { id:"opera", cat:"sight", name:"시드니 오페라 하우스", en:"Sydney Opera House", lat:-33.8568, lng:151.2153, area:"서큘러 키",
    desc:"시드니의 상징. 내부 가이드 투어나 공연 관람을 추천.", tip:"공연 티켓은 미리 예매. 저녁 조명이 켜진 모습도 꼭 보기." },
  { id:"bridge", cat:"sight", name:"하버 브리지", en:"Sydney Harbour Bridge", lat:-33.8523, lng:151.2108, area:"더 록스",
    desc:"도보로 건널 수 있는 아치형 다리. 다리 위에서 보는 오페라 하우스 뷰가 일품.", tip:"동쪽 보행로가 오페라 하우스 쪽 뷰." },
  { id:"climb", cat:"sight", name:"브리지클라임", en:"BridgeClimb Sydney", lat:-33.8578, lng:151.2078, area:"더 록스",
    desc:"하버 브리지 아치 꼭대기까지 올라가는 체험. 신혼여행 버킷리스트 단골.", tip:"선셋 클라임은 일찍 매진. 약 3시간 소요." },
  { id:"rocks", cat:"sight", name:"더 록스", en:"The Rocks Sydney", lat:-33.8599, lng:151.2085, area:"더 록스",
    desc:"시드니에서 가장 오래된 동네. 골목, 펍, 주말 마켓.", tip:"토·일 '더 록스 마켓' 운영." },
  { id:"mca", cat:"sight", name:"현대미술관 (MCA)", en:"Museum of Contemporary Art Australia", lat:-33.8600, lng:151.2090, area:"서큘러 키",
    desc:"무료 입장 현대미술관. 옥상 카페에서 오페라 하우스 뷰.", tip:"" },
  { id:"agnsw", cat:"sight", name:"뉴사우스웨일스 주립미술관", en:"Art Gallery of New South Wales", lat:-33.8688, lng:151.2173, area:"도메인",
    desc:"무료 상설전. 신관 '시드니 모던' 건축도 볼거리.", tip:"" },
  { id:"stmary", cat:"sight", name:"세인트 메리 대성당", en:"St Mary's Cathedral Sydney", lat:-33.8712, lng:151.2133, area:"CBD",
    desc:"고딕 양식의 웅장한 성당. 하이드 파크 바로 옆.", tip:"" },
  { id:"tower", cat:"view", name:"시드니 타워 아이", en:"Sydney Tower Eye", lat:-33.8705, lng:151.2089, area:"CBD",
    desc:"시드니에서 가장 높은 전망대. 도시 360° 파노라마.", tip:"해 질 무렵 방문 추천." },
  { id:"seallife", cat:"sight", name:"씨 라이프 시드니 아쿠아리움", en:"SEA LIFE Sydney Aquarium", lat:-33.8697, lng:151.2021, area:"달링 하버",
    desc:"듀공, 상어 터널이 유명한 수족관.", tip:"근처 와일드라이프 동물원과 콤보 티켓 가능." },
  { id:"taronga", cat:"sight", name:"타롱가 동물원", en:"Taronga Zoo Sydney", lat:-33.8436, lng:151.2413, area:"모스만",
    desc:"코알라·캥거루와 함께 오페라 하우스 뷰. 서큘러 키에서 페리 12분.", tip:"페리 + 스카이 사파리 케이블카 조합 추천." },
  { id:"luna", cat:"sight", name:"루나 파크", en:"Luna Park Sydney", lat:-33.8476, lng:151.2099, area:"밀슨스 포인트",
    desc:"하버 브리지 북단의 레트로 놀이공원. 거대한 얼굴 입구가 포토 스팟.", tip:"" },

  // 뷰포인트
  { id:"mrsmac", cat:"view", name:"미세스 매쿼리스 체어", en:"Mrs Macquarie's Chair", lat:-33.8597, lng:151.2228, area:"보타닉 가든",
    desc:"오페라 하우스와 하버 브리지가 한 프레임에 담기는 최고의 포토 스팟.", tip:"일출·선셋 모두 좋음." },
  { id:"obshill", cat:"view", name:"옵저버토리 힐", en:"Observatory Hill Park", lat:-33.8595, lng:151.2045, area:"더 록스",
    desc:"하버 브리지를 정면에서 바라보는 언덕 공원. 피크닉 명소.", tip:"" },
  { id:"pylon", cat:"view", name:"파일런 전망대", en:"Pylon Lookout Sydney Harbour Bridge", lat:-33.8546, lng:151.2101, area:"하버 브리지",
    desc:"브리지클라임보다 저렴하게 다리 위 뷰를 즐기는 방법.", tip:"" },
  { id:"blueview", cat:"view", name:"블루 마운틴 (에코 포인트)", en:"Echo Point Lookout Katoomba", lat:-33.7320, lng:150.3115, area:"근교 (기차 2시간)",
    desc:"세 자매봉으로 유명한 국립공원. 시드니 근교 당일치기 1순위.", tip:"센트럴역에서 카툼바행 기차. 시닉 월드 함께 방문." },

  // 공원·자연
  { id:"botanic", cat:"nature", name:"왕립 식물원", en:"Royal Botanic Garden Sydney", lat:-33.8642, lng:151.2166, area:"보타닉 가든",
    desc:"오페라 하우스 옆 바닷가 정원. 산책하며 미세스 매쿼리스 체어까지.", tip:"무료 입장." },
  { id:"hyde", cat:"nature", name:"하이드 파크", en:"Hyde Park Sydney", lat:-33.8731, lng:151.2111, area:"CBD",
    desc:"도심 한가운데 공원. 아치볼드 분수와 가로수길.", tip:"" },
  { id:"barangaroo", cat:"nature", name:"바랑가루 리저브", en:"Barangaroo Reserve", lat:-33.8559, lng:151.2017, area:"바랑가루",
    desc:"해안 산책로가 아름다운 공원. 노을 맛집.", tip:"" },
  { id:"b2c", cat:"nature", name:"본다이-쿠지 해안 산책로", en:"Bondi to Coogee Coastal Walk", lat:-33.8990, lng:151.2720, area:"이스턴 비치",
    desc:"절벽 해안을 따라 걷는 약 6km 코스(2~3시간). 브론테, 클로벨리 해변 경유.", tip:"선크림·물 필수. 본다이에서 출발 추천." },

  // 해변
  { id:"bondi", cat:"beach", name:"본다이 비치", en:"Bondi Beach", lat:-33.8915, lng:151.2767, area:"본다이",
    desc:"세계적으로 유명한 서핑 해변.", tip:"CBD에서 버스 333번 또는 기차+버스." },
  { id:"coogee", cat:"beach", name:"쿠지 비치", en:"Coogee Beach", lat:-33.9205, lng:151.2580, area:"쿠지",
    desc:"해안 산책로 종착점. 아늑하고 조용한 해변.", tip:"" },
  { id:"manly", cat:"beach", name:"맨리 비치", en:"Manly Beach", lat:-33.7969, lng:151.2878, area:"맨리",
    desc:"페리로 가는 해변 마을. 페리 위에서 보는 하버 뷰가 하이라이트.", tip:"페리는 오팔 카드/컨택리스 결제 가능." },
  { id:"watsons", cat:"beach", name:"왓슨스 베이", en:"Watsons Bay", lat:-33.8443, lng:151.2817, area:"왓슨스 베이",
    desc:"갭 파크 절벽 전망과 해산물 레스토랑. 페리로 이동.", tip:"Doyles에서 피시앤칩스." },

  // 맛집
  { id:"quay", cat:"food", name:"Quay (퀘이)", en:"Quay Restaurant Sydney", lat:-33.8580, lng:151.2098, area:"서큘러 키",
    desc:"오페라 하우스 뷰 파인다이닝. 특별한 기념일 디너로.", tip:"1~2개월 전 예약 권장." },
  { id:"bennelong", cat:"food", name:"Bennelong (베넬롱)", en:"Bennelong Sydney Opera House", lat:-33.8572, lng:151.2150, area:"오페라 하우스",
    desc:"오페라 하우스 안의 레스토랑. 건축물 내부에서 즐기는 디너.", tip:"예약 필수." },
  { id:"aria", cat:"food", name:"Aria (아리아)", en:"Aria Restaurant Sydney", lat:-33.8601, lng:151.2128, area:"서큘러 키",
    desc:"하버 브리지와 오페라 하우스를 바라보는 모던 오스트레일리안.", tip:"" },
  { id:"mrwong", cat:"food", name:"Mr. Wong (미스터 웡)", en:"Mr. Wong Sydney", lat:-33.8659, lng:151.2077, area:"CBD",
    desc:"인기 캔토니즈 레스토랑. 딤섬과 베이징덕.", tip:"" },
  { id:"fishmkt", cat:"food", name:"시드니 피시 마켓", en:"Sydney Fish Market", lat:-33.8730, lng:151.1925, area:"피어몬트",
    desc:"굴, 랍스터, 사시미 등 신선한 해산물을 저렴하게.", tip:"점심 전 방문이 여유로움." },
  { id:"harrys", cat:"food", name:"해리스 카페 드 휠스", en:"Harry's Cafe de Wheels Woolloomooloo", lat:-33.8695, lng:151.2223, area:"울루물루",
    desc:"1938년부터 이어온 미트파이 노점.", tip:"'타이거 파이' 추천." },
  { id:"icebergs", cat:"food", name:"Icebergs Dining Room", en:"Icebergs Dining Room and Bar", lat:-33.8947, lng:151.2742, area:"본다이",
    desc:"본다이 해변과 수영장이 내려다보이는 레스토랑.", tip:"" },
  { id:"mamak", cat:"food", name:"Mamak (마막)", en:"Mamak Haymarket", lat:-33.8786, lng:151.2036, area:"차이나타운",
    desc:"줄 서서 먹는 말레이시아 로티 맛집.", tip:"" },

  // 카페
  { id:"grounds", cat:"cafe", name:"더 그라운즈 오브 알렉산드리아", en:"The Grounds of Alexandria", lat:-33.9105, lng:151.1947, area:"알렉산드리아",
    desc:"정원 같은 브런치 카페. 사진 찍기 좋은 곳.", tip:"주말은 대기 길어요." },
  { id:"bourke", cat:"cafe", name:"버크 스트리트 베이커리", en:"Bourke Street Bakery Surry Hills", lat:-33.8888, lng:151.2135, area:"서리 힐스",
    desc:"소시지롤과 타르트가 유명한 베이커리.", tip:"" },
  { id:"singleo", cat:"cafe", name:"Single O", en:"Single O Surry Hills", lat:-33.8843, lng:151.2108, area:"서리 힐스",
    desc:"시드니 스페셜티 커피의 대표 주자.", tip:"" },

  // 바·루프탑
  { id:"operabar", cat:"bar", name:"오페라 바", en:"Opera Bar Sydney", lat:-33.8575, lng:151.2141, area:"오페라 하우스",
    desc:"하버 브리지를 바라보며 한잔. 시드니 대표 야외 바.", tip:"선셋 타임 강추." },
  { id:"glenmore", cat:"bar", name:"글렌모어 호텔 루프탑", en:"The Glenmore Hotel", lat:-33.8592, lng:151.2083, area:"더 록스",
    desc:"오페라 하우스가 보이는 펍 루프탑.", tip:"" },
  { id:"blu36", cat:"bar", name:"Blu Bar on 36", en:"Blu Bar on 36 Shangri-La", lat:-33.8615, lng:151.2063, area:"더 록스",
    desc:"샹그릴라 36층 칵테일 바. 야경 데이트 코스.", tip:"" },
  { id:"baxter", cat:"bar", name:"The Baxter Inn", en:"The Baxter Inn", lat:-33.8698, lng:151.2058, area:"CBD",
    desc:"숨겨진 지하 위스키 바.", tip:"" },

  // 쇼핑
  { id:"qvb", cat:"shop", name:"퀸 빅토리아 빌딩 (QVB)", en:"Queen Victoria Building", lat:-33.8718, lng:151.2067, area:"CBD",
    desc:"19세기 로마네스크 양식의 아름다운 쇼핑 아케이드.", tip:"" },
  { id:"strand", cat:"shop", name:"스트랜드 아케이드", en:"The Strand Arcade Sydney", lat:-33.8697, lng:151.2073, area:"CBD",
    desc:"빅토리아 양식 아케이드. 호주 디자이너 브랜드.", tip:"" },
  { id:"pitt", cat:"shop", name:"피트 스트리트 몰", en:"Pitt Street Mall", lat:-33.8700, lng:151.2085, area:"CBD",
    desc:"시드니 대표 보행자 쇼핑 거리.", tip:"" },
  { id:"paddys", cat:"shop", name:"패디스 마켓", en:"Paddy's Markets Haymarket", lat:-33.8800, lng:151.2030, area:"차이나타운",
    desc:"기념품 쇼핑하기 좋은 재래시장.", tip:"수~일 운영." },
  { id:"darling", cat:"sight", name:"달링 하버", en:"Darling Harbour", lat:-33.8748, lng:151.1987, area:"달링 하버",
    desc:"레스토랑과 바가 모인 항구. 주말 밤 불꽃놀이(시즌별).", tip:"" },

  // 숙소
  { id:"parkhyatt", cat:"hotel", name:"파크 하얏트 시드니", en:"Park Hyatt Sydney", lat:-33.8556, lng:151.2097, area:"더 록스",
    desc:"오페라 하우스 정면 뷰 객실. 신혼여행 인기 호텔.", tip:"" },
  { id:"fourseasons", cat:"hotel", name:"포시즌스 시드니", en:"Four Seasons Hotel Sydney", lat:-33.8613, lng:151.2078, area:"서큘러 키",
    desc:"서큘러 키 도보권. 하버 뷰 객실.", tip:"" },
  { id:"shangrila", cat:"hotel", name:"샹그릴라 시드니", en:"Shangri-La Sydney", lat:-33.8615, lng:151.2066, area:"더 록스",
    desc:"고층 하버 뷰가 뛰어난 호텔.", tip:"" },
  { id:"pierone", cat:"hotel", name:"피어 원 시드니 하버", en:"Pier One Sydney Harbour", lat:-33.8549, lng:151.2085, area:"월시 베이",
    desc:"하버 브리지 바로 아래, 부두 위 부티크 호텔.", tip:"" },

  // 교통
  { id:"cquay", cat:"trans", name:"서큘러 키 페리 터미널", en:"Circular Quay Wharf", lat:-33.8611, lng:151.2108, area:"서큘러 키",
    desc:"맨리·타롱가·왓슨스 베이행 페리 출발지. 기차역 연결.", tip:"" },
  { id:"central", cat:"trans", name:"센트럴역", en:"Central Station Sydney", lat:-33.8832, lng:151.2070, area:"헤이마켓",
    desc:"공항철도 및 블루 마운틴행 기차.", tip:"" },
  { id:"syd", cat:"trans", name:"시드니 공항", en:"Sydney Airport International Terminal", lat:-33.9366, lng:151.1655, area:"마스콧",
    desc:"공항철도로 시티까지 약 15분.", tip:"" },
];

export const DAY_COLORS = ["#e8590c","#1c7ed6","#2f9e44","#ae3ec9","#f08c00","#0c8599","#c2255c","#5c940d","#3b5bdb","#862e9c"];

export const SYDNEY_SAMPLE = [
  { stops:["syd","parkhyatt","cquay","opera","botanic","mrsmac","operabar","bennelong"], note:"도착 → 체크인 → 하버 산책 → 오페라 바 선셋 → 디너" },
  { stops:["rocks","mca","climb","obshill","barangaroo","darling","glenmore"], note:"더 록스 골목 → 브리지클라임 → 바랑가루 노을" },
  { stops:["bondi","icebergs","b2c","coogee","bourke"], note:"본다이 브런치 → 해안 산책로 → 쿠지" },
  { stops:["cquay","taronga","manly","quay"], note:"페리 데이: 타롱가 동물원 → 맨리 → 기념일 디너" },
  { stops:["qvb","strand","pitt","hyde","stmary","agnsw","harrys","mrwong","blu36"], note:"시티 쇼핑 & 미술관 → 야경 칵테일" },
  { stops:["central","blueview"], note:"(선택) 블루 마운틴 당일치기" },
];

// ---------- 멜버른 ----------
export const MELBOURNE_PLACES = [
  { id:"m_fed", cat:"sight", name:"페더레이션 스퀘어", en:"Federation Square", lat:-37.8180, lng:144.9691, area:"CBD",
    desc:"멜버른 도심의 광장. 주변 미술관·강변 산책의 출발점.", tip:"" },
  { id:"m_flinders", cat:"sight", name:"플린더스 스트리트역", en:"Flinders Street Station", lat:-37.8183, lng:144.9671, area:"CBD",
    desc:"노란 외관의 멜버른 상징 기차역.", tip:"CBD 안 트램은 무료(Free Tram Zone)." },
  { id:"m_hosier", cat:"sight", name:"호시어 레인", en:"Hosier Lane", lat:-37.8165, lng:144.9690, area:"CBD",
    desc:"그래피티로 가득한 골목. 커플 사진 명소.", tip:"" },
  { id:"m_ngv", cat:"sight", name:"빅토리아 국립미술관 (NGV)", en:"NGV International", lat:-37.8226, lng:144.9689, area:"사우스뱅크",
    desc:"무료 상설전. 스테인드글라스 천장의 그레이트 홀.", tip:"" },
  { id:"m_reb", cat:"sight", name:"왕립 전시관", en:"Royal Exhibition Building", lat:-37.8047, lng:144.9717, area:"칼턴",
    desc:"유네스코 세계유산. 칼턴 가든과 함께 산책.", tip:"" },
  { id:"m_eureka", cat:"view", name:"멜버른 스카이덱", en:"Melbourne Skydeck", lat:-37.8214, lng:144.9646, area:"사우스뱅크",
    desc:"유레카 타워 88층 전망대.", tip:"해 질 무렵 추천." },
  { id:"m_shrine", cat:"view", name:"전쟁기념관 (슈라인)", en:"Shrine of Remembrance", lat:-37.8305, lng:144.9734, area:"사우스 야라",
    desc:"테라스에서 도심 스카이라인이 한눈에.", tip:"" },
  { id:"m_rbg", cat:"nature", name:"왕립 식물원", en:"Royal Botanic Gardens Victoria", lat:-37.8304, lng:144.9796, area:"사우스 야라",
    desc:"호수와 잔디밭이 아름다운 정원. 피크닉 추천.", tip:"" },
  { id:"m_gor", cat:"view", name:"그레이트 오션 로드 (12사도)", en:"The Twelve Apostles", lat:-38.6662, lng:143.1050, area:"근교 (차로 3~4시간)",
    desc:"해안 절벽 드라이브의 하이라이트. 투어 또는 렌터카 당일치기.", tip:"일몰 시간대가 가장 아름다워요." },
  { id:"m_phillip", cat:"nature", name:"필립 아일랜드 펭귄 퍼레이드", en:"Penguin Parade Phillip Island", lat:-38.5106, lng:145.1506, area:"근교 (차로 2시간)",
    desc:"해 질 녘 해변으로 돌아오는 꼬마펭귄 관람.", tip:"" },
  { id:"m_yarra", cat:"nature", name:"야라 밸리 와이너리", en:"Domaine Chandon Yarra Valley", lat:-37.7015, lng:145.4285, area:"근교 (차로 1시간)",
    desc:"와이너리 투어·열기구로 유명한 와인 산지.", tip:"" },
  { id:"m_stkilda", cat:"beach", name:"세인트킬다 비치", en:"St Kilda Beach", lat:-37.8679, lng:144.9740, area:"세인트킬다",
    desc:"트램으로 가는 해변. 피어 끝에서 꼬마펭귄을 볼 수도.", tip:"" },
  { id:"m_brighton", cat:"beach", name:"브라이턴 비치 박스", en:"Brighton Bathing Boxes", lat:-37.9175, lng:144.9867, area:"브라이턴",
    desc:"알록달록한 비치 박스가 늘어선 포토 스팟.", tip:"" },
  { id:"m_chin", cat:"food", name:"Chin Chin (친친)", en:"Chin Chin Melbourne", lat:-37.8155, lng:144.9708, area:"CBD",
    desc:"줄 서서 먹는 모던 타이 레스토랑.", tip:"" },
  { id:"m_vue", cat:"food", name:"Vue de monde", en:"Vue de monde", lat:-37.8189, lng:144.9577, area:"CBD",
    desc:"리알토 55층 파인다이닝. 기념일 디너로.", tip:"예약 필수." },
  { id:"m_lygon", cat:"food", name:"라이곤 스트리트", en:"Lygon Street Carlton", lat:-37.7980, lng:144.9670, area:"칼턴",
    desc:"이탈리안 레스토랑·젤라토 거리.", tip:"" },
  { id:"m_degraves", cat:"cafe", name:"디그레이브스 스트리트", en:"Degraves Street", lat:-37.8170, lng:144.9656, area:"CBD",
    desc:"골목 카페가 모인 멜버른 커피 문화의 상징.", tip:"" },
  { id:"m_patricia", cat:"cafe", name:"Patricia Coffee Brewers", en:"Patricia Coffee Brewers", lat:-37.8146, lng:144.9585, area:"CBD",
    desc:"스탠딩 전용 스페셜티 커피 명소.", tip:"" },
  { id:"m_lune", cat:"cafe", name:"Lune 크루아상", en:"Lune Croissanterie Fitzroy", lat:-37.7985, lng:144.9790, area:"피츠로이",
    desc:"세계 최고라는 평을 듣는 크루아상.", tip:"오전에 매진되기 쉬워요." },
  { id:"m_rooftop", cat:"bar", name:"루프탑 바 (커틴 하우스)", en:"Rooftop Bar Curtin House", lat:-37.8114, lng:144.9658, area:"CBD",
    desc:"도심 루프탑 바. 여름엔 루프탑 시네마도.", tip:"" },
  { id:"m_qvm", cat:"shop", name:"퀸 빅토리아 마켓", en:"Queen Victoria Market", lat:-37.8076, lng:144.9568, area:"CBD",
    desc:"먹거리·기념품 가득한 재래시장.", tip:"월·금요일은 휴무가 많아요." },
  { id:"m_langham", cat:"hotel", name:"랭햄 멜버른", en:"The Langham Melbourne", lat:-37.8207, lng:144.9633, area:"사우스뱅크",
    desc:"야라 강변 럭셔리 호텔.", tip:"" },
  { id:"m_sxs", cat:"trans", name:"서던크로스역", en:"Southern Cross Station", lat:-37.8183, lng:144.9525, area:"CBD",
    desc:"공항 스카이버스·지방 열차 출발역.", tip:"" },
  { id:"m_mel", cat:"trans", name:"멜버른 공항", en:"Melbourne Airport", lat:-37.6690, lng:144.8410, area:"툴라마린",
    desc:"스카이버스로 서던크로스역까지 약 30분.", tip:"" },
];
export const MELBOURNE_SAMPLE = [
  { stops:["m_mel","m_langham","m_fed","m_hosier","m_degraves","m_eureka","m_chin"], note:"도착 → 골목 카페 → 스카이덱 야경" },
  { stops:["m_qvm","m_reb","m_lygon","m_lune","m_ngv","m_rooftop"], note:"마켓 → 칼턴 → 미술관 → 루프탑" },
  { stops:["m_rbg","m_shrine","m_stkilda","m_brighton","m_vue"], note:"정원 → 해변 → 기념일 디너" },
  { stops:["m_gor"], note:"(선택) 그레이트 오션 로드 당일 투어" },
];

// ---------- 골드코스트 ----------
export const GOLDCOAST_PLACES = [
  { id:"gc_surfers", cat:"beach", name:"서퍼스 파라다이스 비치", en:"Surfers Paradise Beach", lat:-28.0000, lng:153.4310, area:"서퍼스 파라다이스",
    desc:"골드코스트 대표 해변. 고층 빌딩과 백사장.", tip:"" },
  { id:"gc_burleigh", cat:"nature", name:"벌리 헤즈", en:"Burleigh Head National Park", lat:-28.0890, lng:153.4560, area:"벌리 헤즈",
    desc:"해안 산책로와 서퍼스 파라다이스 스카이라인 뷰.", tip:"일몰 피크닉 명소." },
  { id:"gc_kirra", cat:"beach", name:"커라 비치", en:"Kirra Beach", lat:-28.1650, lng:153.5300, area:"쿨랑가타",
    desc:"한적하고 맑은 남쪽 해변.", tip:"" },
  { id:"gc_q1", cat:"view", name:"스카이포인트 전망대 (Q1)", en:"SkyPoint Observation Deck", lat:-28.0062, lng:153.4294, area:"서퍼스 파라다이스",
    desc:"Q1 빌딩 77층 전망대.", tip:"" },
  { id:"gc_springbrook", cat:"nature", name:"스프링브룩 내추럴 브리지", en:"Natural Bridge Springbrook National Park", lat:-28.2339, lng:153.2745, area:"근교 (차로 1시간)",
    desc:"밤이면 반딧불이(글로웜)가 빛나는 동굴 폭포.", tip:"글로웜 투어는 야간." },
  { id:"gc_tamborine", cat:"nature", name:"탬버린 마운틴", en:"Tamborine Rainforest Skywalk", lat:-27.9180, lng:153.1800, area:"근교 (차로 50분)",
    desc:"열대우림 스카이워크와 와이너리.", tip:"" },
  { id:"gc_currumbin", cat:"sight", name:"커럼빈 야생동물 보호구역", en:"Currumbin Wildlife Sanctuary", lat:-28.1373, lng:153.4880, area:"커럼빈",
    desc:"코알라 안기, 캥거루 먹이주기.", tip:"" },
  { id:"gc_seaworld", cat:"sight", name:"씨월드", en:"Sea World Gold Coast", lat:-27.9570, lng:153.4256, area:"메인 비치",
    desc:"돌고래 쇼와 놀이기구.", tip:"" },
  { id:"gc_movieworld", cat:"sight", name:"무비월드", en:"Warner Bros. Movie World", lat:-27.9073, lng:153.3127, area:"옥슨포드",
    desc:"영화 테마파크.", tip:"" },
  { id:"gc_hota", cat:"sight", name:"HOTA 아트센터", en:"HOTA Home of the Arts", lat:-28.0080, lng:153.4170, area:"서퍼스 파라다이스",
    desc:"미술관과 공원, 주말 마켓.", tip:"" },
  { id:"gc_rick", cat:"food", name:"Rick Shores", en:"Rick Shores Burleigh Heads", lat:-28.0866, lng:153.4545, area:"벌리 헤즈",
    desc:"파도 바로 앞 아시안 퓨전 레스토랑.", tip:"예약 추천." },
  { id:"gc_paddock", cat:"cafe", name:"Paddock Bakery", en:"Paddock Bakery Miami", lat:-28.0700, lng:153.4400, area:"마이애미",
    desc:"오두막 감성의 인기 베이커리 카페.", tip:"" },
  { id:"gc_justin", cat:"bar", name:"Justin Lane", en:"Justin Lane Burleigh", lat:-28.0867, lng:153.4513, area:"벌리 헤즈",
    desc:"루프탑 피자 & 칵테일 바.", tip:"" },
  { id:"gc_pacific", cat:"shop", name:"퍼시픽 페어", en:"Pacific Fair Shopping Centre", lat:-28.0360, lng:153.4310, area:"브로드비치",
    desc:"골드코스트 최대 쇼핑몰.", tip:"" },
  { id:"gc_star", cat:"hotel", name:"더 스타 골드코스트", en:"The Star Gold Coast", lat:-28.0310, lng:153.4300, area:"브로드비치",
    desc:"브로드비치 리조트 호텔.", tip:"" },
  { id:"gc_ool", cat:"trans", name:"골드코스트 공항", en:"Gold Coast Airport", lat:-28.1644, lng:153.5047, area:"쿨랑가타",
    desc:"서퍼스 파라다이스까지 버스·택시 약 30~40분.", tip:"" },
];
export const GOLDCOAST_SAMPLE = [
  { stops:["gc_ool","gc_star","gc_surfers","gc_q1"], note:"도착 → 해변 → 전망대 야경" },
  { stops:["gc_paddock","gc_burleigh","gc_rick","gc_justin"], note:"벌리 헤즈 데이" },
  { stops:["gc_tamborine","gc_springbrook"], note:"열대우림 & 글로웜 투어" },
];

// ---------- 케언즈 ----------
export const CAIRNS_PLACES = [
  { id:"c_lagoon", cat:"sight", name:"에스플러네이드 라군", en:"Cairns Esplanade Lagoon", lat:-16.9196, lng:145.7790, area:"케언즈 시티",
    desc:"바다 옆 무료 야외 수영장.", tip:"" },
  { id:"c_gbr", cat:"nature", name:"그레이트 배리어 리프 (그린 아일랜드)", en:"Green Island Great Barrier Reef", lat:-16.7590, lng:145.9710, area:"페리 50분",
    desc:"산호초 스노클링·글라스 보텀 보트.", tip:"리프 플릿 터미널에서 출발." },
  { id:"c_kuranda", cat:"sight", name:"쿠란다 마을", en:"Kuranda Village", lat:-16.8190, lng:145.6380, area:"쿠란다",
    desc:"열대우림 속 예술가 마을. 시닉 레일웨이로 가요.", tip:"갈 땐 기차, 올 땐 스카이레일 조합 추천." },
  { id:"c_skyrail", cat:"view", name:"스카이레일 열대우림 케이블웨이", en:"Skyrail Rainforest Cableway", lat:-16.8410, lng:145.6920, area:"스미스필드",
    desc:"열대우림 위를 지나는 7.5km 케이블카.", tip:"" },
  { id:"c_mossman", cat:"nature", name:"모스만 협곡 (데인트리)", en:"Mossman Gorge Centre", lat:-16.4720, lng:145.3330, area:"근교 (차로 1시간 20분)",
    desc:"세계에서 가장 오래된 열대우림 데인트리.", tip:"" },
  { id:"c_palm", cat:"beach", name:"팜 코브", en:"Palm Cove Beach", lat:-16.7470, lng:145.6720, area:"팜 코브",
    desc:"야자수 가로수의 조용한 리조트 해변.", tip:"" },
  { id:"c_port", cat:"beach", name:"포트 더글러스 포 마일 비치", en:"Four Mile Beach Port Douglas", lat:-16.4900, lng:145.4650, area:"포트 더글러스",
    desc:"허니무너가 사랑하는 해변 마을.", tip:"" },
  { id:"c_night", cat:"shop", name:"케언즈 나이트 마켓", en:"Cairns Night Markets", lat:-16.9213, lng:145.7785, area:"케언즈 시티",
    desc:"기념품·푸드코트가 있는 야시장.", tip:"" },
  { id:"c_ochre", cat:"food", name:"Ochre Restaurant", en:"Ochre Restaurant Cairns", lat:-16.9235, lng:145.7785, area:"케언즈 시티",
    desc:"캥거루·악어 등 호주 식재료 요리.", tip:"" },
  { id:"c_salt", cat:"bar", name:"Salt House", en:"Salt House Cairns", lat:-16.9215, lng:145.7820, area:"마리나",
    desc:"마리나 뷰 레스토랑 & 바.", tip:"선셋 추천." },
  { id:"c_riley", cat:"hotel", name:"크리스탈브룩 라일리", en:"Crystalbrook Riley", lat:-16.9150, lng:145.7770, area:"케언즈 시티",
    desc:"라군 수영장이 있는 에스플러네이드 호텔.", tip:"" },
  { id:"c_reef", cat:"trans", name:"리프 플릿 터미널", en:"Reef Fleet Terminal", lat:-16.9230, lng:145.7810, area:"마리나",
    desc:"그레이트 배리어 리프 투어 보트 출발지.", tip:"" },
  { id:"c_cns", cat:"trans", name:"케언즈 공항", en:"Cairns Airport", lat:-16.8858, lng:145.7553, area:"케언즈",
    desc:"시내까지 차로 약 10분.", tip:"" },
];
export const CAIRNS_SAMPLE = [
  { stops:["c_cns","c_riley","c_lagoon","c_night","c_ochre"], note:"도착 → 라군 → 야시장" },
  { stops:["c_reef","c_gbr","c_salt"], note:"그레이트 배리어 리프 데이" },
  { stops:["c_kuranda","c_skyrail","c_palm"], note:"쿠란다 → 스카이레일 → 팜 코브" },
];

export const CITIES = {
  sydney:    { id:"sydney", name:"시드니", flag:"🇦🇺", center:{ lat:-33.8650, lng:151.2094 }, zoom:14, suffix:"Sydney NSW",
               airbnb:"Sydney--NSW--Australia", currency:"AUD", visa:"호주 ETA(전자여행허가) 신청 — 'AustralianETA' 앱", plug:"I 타입 · 230V", places:SYDNEY_PLACES, sample:SYDNEY_SAMPLE,
               keySpots:[["cquay","서큘러 키"], ["qvb","시티(QVB)"], ["darling","달링 하버"], ["bondi","본다이"]] },
  melbourne: { id:"melbourne", name:"멜버른", flag:"🇦🇺", center:{ lat:-37.8136, lng:144.9631 }, zoom:14, suffix:"Melbourne VIC",
               airbnb:"Melbourne--VIC--Australia", currency:"AUD", visa:"호주 ETA(전자여행허가) 신청 — 'AustralianETA' 앱", plug:"I 타입 · 230V", places:MELBOURNE_PLACES, sample:MELBOURNE_SAMPLE,
               keySpots:[["m_flinders","플린더스역"], ["m_qvm","퀸 빅토리아 마켓"], ["m_stkilda","세인트킬다"]] },
  goldcoast: { id:"goldcoast", name:"골드코스트", flag:"🇦🇺", center:{ lat:-28.0167, lng:153.4000 }, zoom:12, suffix:"Gold Coast QLD",
               airbnb:"Gold-Coast--QLD--Australia", currency:"AUD", visa:"호주 ETA(전자여행허가) 신청 — 'AustralianETA' 앱", plug:"I 타입 · 230V", places:GOLDCOAST_PLACES, sample:GOLDCOAST_SAMPLE,
               keySpots:[["gc_surfers","서퍼스 파라다이스"], ["gc_burleigh","벌리 헤즈"], ["gc_ool","공항"]] },
  cairns:    { id:"cairns", name:"케언즈", flag:"🇦🇺", center:{ lat:-16.9186, lng:145.7781 }, zoom:13, suffix:"Cairns QLD",
               airbnb:"Cairns--QLD--Australia", currency:"AUD", visa:"호주 ETA(전자여행허가) 신청 — 'AustralianETA' 앱", plug:"I 타입 · 230V", places:CAIRNS_PLACES, sample:CAIRNS_SAMPLE,
               keySpots:[["c_lagoon","에스플러네이드"], ["c_reef","리프 터미널"], ["c_cns","공항"]] },
  hawaii:    { id:"hawaii", name:"하와이 (오아후)", flag:"🇺🇸", center:{ lat:21.2850, lng:-157.8357 }, zoom:13, suffix:"Honolulu HI",
               airbnb:"Honolulu--HI--United-States", currency:"USD", visa:"미국 ESTA(전자여행허가) 신청 — 공식 사이트 esta.cbp.dhs.gov", plug:"A·B 타입 · 110V",
               places:HAWAII_PLACES, sample:HAWAII_SAMPLE,
               keySpots:[["hi_waikiki","와이키키"], ["hi_ala","알라 모아나"], ["hi_hnl","공항"]] },
  bali:      { id:"bali", name:"발리", flag:"🇮🇩", center:{ lat:-8.6500, lng:115.2000 }, zoom:10, suffix:"Bali Indonesia",
               airbnb:"Bali--Indonesia", currency:"IDR", visa:"인도네시아 전자 도착비자(e-VOA) 신청과 발리 관광세 납부", plug:"C·F 타입 · 230V",
               places:BALI_PLACES, sample:BALI_SAMPLE,
               keySpots:[["ba_seminyak","스미냑"], ["ba_ubud","우붓"], ["ba_dps","공항"]] },
  paris:     { id:"paris", name:"파리", flag:"🇫🇷", center:{ lat:48.8566, lng:2.3522 }, zoom:13, suffix:"Paris France",
               airbnb:"Paris--France", currency:"EUR", visa:"유럽 입국 조건 확인 (ETIAS 시행 여부)", plug:"C·E 타입 · 230V",
               places:PARIS_PLACES, sample:PARIS_SAMPLE,
               keySpots:[["pa_louvre","루브르"], ["pa_eiffel","에펠탑"], ["pa_vosges","마레"]] },
  tokyo:     { id:"tokyo", name:"도쿄", flag:"🇯🇵", center:{ lat:35.6812, lng:139.7671 }, zoom:12, suffix:"Tokyo Japan",
               airbnb:"Tokyo--Japan", currency:"JPY", visa:"Visit Japan Web 입국 정보 등록", plug:"A 타입 · 100V",
               places:TOKYO_PLACES, sample:TOKYO_SAMPLE,
               keySpots:[["tk_shibuya","시부야"], ["tk_parkhyatt","신주쿠"], ["tk_ginza","긴자"]] },
  danang:    { id:"danang", name:"다낭 · 호이안", flag:"🇻🇳", center:{ lat:16.0544, lng:108.2022 }, zoom:12, suffix:"Da Nang Vietnam",
               airbnb:"Da-Nang--Vietnam", currency:"VND", visa:"베트남 입국 조건 확인 (무비자 체류 기간·여권 유효기간)", plug:"A·C 타입 · 220V",
               places:DANANG_PLACES, sample:DANANG_SAMPLE,
               keySpots:[["dn_mykhe","미케 비치"], ["dn_hoian","호이안"], ["dn_dad","공항"]] },
};
