// 인기 신혼여행지 추천 장소. 좌표는 대략적인 위치예요 (scripts/verify-places.mjs로 OpenStreetMap과 대조)

// ---------- 하와이 (오아후) ----------
export const HAWAII_PLACES = [
  { id:"hi_waikiki", cat:"beach", name:"와이키키 비치", en:"Waikiki Beach", lat:21.2766, lng:-157.8270, area:"와이키키",
    desc:"하와이 여행의 시작. 서핑 레슨·선셋 산책.", tip:"해 질 녘 다이아몬드 헤드 쪽 풍경이 가장 예뻐요." },
  { id:"hi_diamond", cat:"view", name:"다이아몬드 헤드", en:"Diamond Head State Monument", lat:21.2614, lng:-157.8059, area:"와이키키 동쪽",
    desc:"분화구 정상까지 왕복 1.5~2시간 하이킹. 와이키키 전경.", tip:"입장 사전 예약 필수. 더위 전 이른 아침 추천." },
  { id:"hi_hanauma", cat:"nature", name:"하나우마 베이", en:"Hanauma Bay", lat:21.2690, lng:-157.6938, area:"동부 해안",
    desc:"거북이·열대어를 만나는 스노클링 명소.", tip:"온라인 예약제, 화·수 휴무. 보호 교육 영상 시청 후 입장." },
  { id:"hi_makapuu", cat:"view", name:"마카푸우 등대 트레일", en:"Makapuu Point", lat:21.3036, lng:-157.6497, area:"동부 해안",
    desc:"완만한 포장길 끝에 펼쳐지는 바다 전망. 겨울엔 고래도.", tip:"그늘이 없어 물·모자 필수." },
  { id:"hi_lanikai", cat:"beach", name:"라니카이 비치", en:"Lanikai Beach", lat:21.3931, lng:-157.7154, area:"카일루아",
    desc:"에메랄드빛 물과 두 개의 섬이 보이는 조용한 해변.", tip:"주차가 어려워요. 카일루아에 세우고 걸어가기." },
  { id:"hi_kailua", cat:"beach", name:"카일루아 비치", en:"Kailua Beach Park", lat:21.3973, lng:-157.7275, area:"카일루아",
    desc:"카약·패들보드 타기 좋은 넓은 해변.", tip:"" },
  { id:"hi_kualoa", cat:"nature", name:"쿠알로아 랜치", en:"Kualoa Ranch", lat:21.5208, lng:-157.8370, area:"동북부",
    desc:"쥬라기 공원 촬영지. UTV·승마·영화 촬영지 투어.", tip:"투어는 미리 예약." },
  { id:"hi_giovanni", cat:"food", name:"지오바니 새우 트럭", en:"Giovanni's Shrimp Truck", lat:21.5807, lng:-158.1046, area:"할레이와",
    desc:"갈릭 버터 새우의 원조 푸드트럭.", tip:"" },
  { id:"hi_waimea", cat:"beach", name:"와이메아 베이", en:"Waimea Bay", lat:21.6411, lng:-158.0651, area:"노스쇼어",
    desc:"여름엔 잔잔한 바다, 겨울엔 거대한 파도.", tip:"겨울(11~3월)엔 수영 금지일 때가 많아요." },
  { id:"hi_haleiwa", cat:"sight", name:"할레이와 타운", en:"Haleiwa", lat:21.5928, lng:-158.1031, area:"노스쇼어",
    desc:"서핑 마을. 셰이브 아이스와 갤러리 구경.", tip:"마츠모토 셰이브 아이스 추천." },
  { id:"hi_pearl", cat:"sight", name:"진주만 국립 기념관", en:"Pearl Harbor National Memorial", lat:21.3678, lng:-157.9390, area:"진주만",
    desc:"USS 애리조나 기념관.", tip:"기념관 보트는 무료지만 온라인 예약 권장." },
  { id:"hi_manoa", cat:"nature", name:"마노아 폭포 트레일", en:"Manoa Falls Trail", lat:21.3330, lng:-157.8010, area:"마노아",
    desc:"열대우림 속 왕복 1시간 하이킹.", tip:"진흙길이라 운동화 필수." },
  { id:"hi_kakaako", cat:"sight", name:"카카아코 벽화 거리", en:"Kakaako", lat:21.2969, lng:-157.8585, area:"카카아코",
    desc:"알록달록한 대형 벽화 사이 커플 사진 명소.", tip:"" },
  { id:"hi_ala", cat:"shop", name:"알라 모아나 센터", en:"Ala Moana Center", lat:21.2910, lng:-157.8434, area:"알라 모아나",
    desc:"하와이 최대 쇼핑몰.", tip:"" },
  { id:"hi_imp", cat:"shop", name:"인터내셔널 마켓 플레이스", en:"International Market Place", lat:21.2780, lng:-157.8285, area:"와이키키",
    desc:"반얀트리 아래 쇼핑몰.", tip:"" },
  { id:"hi_leonard", cat:"cafe", name:"레오나드 베이커리", en:"Leonard's Bakery", lat:21.2847, lng:-157.8132, area:"카파훌루",
    desc:"갓 튀긴 말라사다(포르투갈식 도넛).", tip:"" },
  { id:"hi_duke", cat:"food", name:"듀크스 와이키키", en:"Duke's Waikiki", lat:21.2779, lng:-157.8292, area:"와이키키",
    desc:"바다 바로 앞 하와이안 레스토랑.", tip:"선셋 시간 예약 추천. 디저트 훌라 파이." },
  { id:"hi_maitai", cat:"bar", name:"마이타이 바 (로열 하와이안)", en:"Mai Tai Bar Royal Hawaiian", lat:21.2774, lng:-157.8296, area:"와이키키",
    desc:"핑크 팰리스의 해변 바. 라이브 음악과 마이타이.", tip:"" },
  { id:"hi_royal", cat:"hotel", name:"로열 하와이안", en:"The Royal Hawaiian", lat:21.2774, lng:-157.8298, area:"와이키키",
    desc:"분홍빛 '태평양의 핑크 팰리스'.", tip:"" },
  { id:"hi_hnl", cat:"trans", name:"호놀룰루 공항", en:"Daniel K. Inouye International Airport", lat:21.3245, lng:-157.9251, area:"호놀룰루",
    desc:"와이키키까지 차로 약 25~40분.", tip:"" },
];
export const HAWAII_SAMPLE = [
  { stops:["hi_hnl","hi_royal","hi_waikiki","hi_imp","hi_maitai"], note:"도착 → 와이키키 산책 → 선셋 마이타이" },
  { stops:["hi_diamond","hi_leonard","hi_kakaako","hi_ala","hi_duke"], note:"다이아몬드 헤드 아침 하이킹 → 카카아코 → 쇼핑" },
  { stops:["hi_hanauma","hi_makapuu","hi_lanikai","hi_kailua"], note:"동부 해안 드라이브 · 스노클링" },
  { stops:["hi_kualoa","hi_waimea","hi_haleiwa","hi_giovanni"], note:"노스쇼어 일주" },
  { stops:["hi_pearl","hi_manoa"], note:"진주만 → 마노아 폭포" },
];

// ---------- 발리 ----------
export const BALI_PLACES = [
  { id:"ba_uluwatu", cat:"sight", name:"울루와뚜 사원", en:"Uluwatu Temple", lat:-8.8291, lng:115.0849, area:"울루와뚜",
    desc:"절벽 끝 사원. 해 질 녘 께짝 댄스 공연.", tip:"원숭이가 물건을 채가요. 선글라스·모자 조심." },
  { id:"ba_tanahlot", cat:"sight", name:"따나롯 사원", en:"Tanah Lot", lat:-8.6212, lng:115.0868, area:"따바난",
    desc:"바다 위 바위섬 사원. 발리 대표 선셋 명소.", tip:"썰물 때는 사원 앞까지 걸어갈 수 있어요." },
  { id:"ba_seminyak", cat:"beach", name:"스미냑 비치", en:"Seminyak Beach", lat:-8.6913, lng:115.1567, area:"스미냑",
    desc:"빈백 소파에서 즐기는 선셋 비치.", tip:"" },
  { id:"ba_potato", cat:"bar", name:"포테이토 헤드 비치클럽", en:"Potato Head Beach Club", lat:-8.6797, lng:115.1532, area:"스미냑",
    desc:"인피니티 풀이 있는 대표 비치클럽.", tip:"선셋 시간대 자리 경쟁이 치열해요." },
  { id:"ba_finns", cat:"bar", name:"핀스 비치클럽", en:"Finns Beach Club", lat:-8.6660, lng:115.1385, area:"짱구 (베라와)",
    desc:"짱구의 대형 비치클럽.", tip:"" },
  { id:"ba_jimbaran", cat:"food", name:"짐바란 씨푸드 디너", en:"Jimbaran Beach", lat:-8.7745, lng:115.1660, area:"짐바란",
    desc:"모래사장 위 테이블에서 즐기는 해산물 바비큐.", tip:"해 지기 30분 전 도착." },
  { id:"ba_ubud", cat:"sight", name:"우붓 왕궁", en:"Ubud Palace", lat:-8.5069, lng:115.2625, area:"우붓",
    desc:"우붓 중심의 왕궁. 저녁 레공 댄스 공연.", tip:"건너편 우붓 시장도 함께." },
  { id:"ba_monkey", cat:"nature", name:"몽키 포레스트", en:"Sacred Monkey Forest Sanctuary", lat:-8.5188, lng:115.2585, area:"우붓",
    desc:"원숭이가 사는 신성한 숲과 사원.", tip:"음식·반짝이는 물건은 가방 안에." },
  { id:"ba_campuhan", cat:"nature", name:"짬뿌한 릿지 워크", en:"Campuhan Ridge Walk", lat:-8.5030, lng:115.2540, area:"우붓",
    desc:"능선을 따라 걷는 초록빛 산책로.", tip:"이른 아침이나 해 질 녘 추천." },
  { id:"ba_bebek", cat:"food", name:"베벡 벵길", en:"Bebek Bengil", lat:-8.5143, lng:115.2650, area:"우붓",
    desc:"논 뷰를 보며 먹는 바삭한 오리 요리.", tip:"" },
  { id:"ba_tegallalang", cat:"view", name:"뜨갈랄랑 계단식 논", en:"Tegallalang Rice Terrace", lat:-8.4312, lng:115.2793, area:"우붓 북쪽",
    desc:"정글 그네와 계단식 논 포토 스폿.", tip:"오전 9시 전이 한산해요." },
  { id:"ba_tirta", cat:"sight", name:"띠르따 엠풀 사원", en:"Tirta Empul", lat:-8.4153, lng:115.3153, area:"따막시링",
    desc:"성스러운 샘물에서 하는 정화 의식.", tip:"사롱 대여 가능." },
  { id:"ba_ulundanu", cat:"sight", name:"울룬 다누 브라딴 사원", en:"Pura Ulun Danu Bratan", lat:-8.2752, lng:115.1668, area:"브두굴",
    desc:"호수 위에 떠 있는 듯한 사원. 선선한 고원.", tip:"얇은 겉옷 챙기기." },
  { id:"ba_lempuyang", cat:"view", name:"렘뿌양 사원 (천국의 문)", en:"Lempuyang Temple", lat:-8.3914, lng:115.6311, area:"동부 (차로 2시간 반)",
    desc:"아궁산을 배경으로 한 '천국의 문' 사진.", tip:"새벽 출발 추천. 사진 대기가 길어요." },
  { id:"ba_kelingking", cat:"beach", name:"끌링킹 비치 (누사 페니다)", en:"Kelingking Beach", lat:-8.7509, lng:115.4746, area:"누사 페니다",
    desc:"티라노사우루스 모양 절벽 뷰.", tip:"사누르 항에서 스피드보트 약 40분. 당일 투어가 편해요." },
  { id:"ba_sisterfields", cat:"cafe", name:"시스터필즈", en:"Sisterfields", lat:-8.6830, lng:115.1640, area:"스미냑",
    desc:"브런치 맛집.", tip:"" },
  { id:"ba_mulia", cat:"hotel", name:"더 물리아 (누사두아)", en:"The Mulia Bali", lat:-8.8168, lng:115.2235, area:"누사두아",
    desc:"허니문 인기 리조트.", tip:"" },
  { id:"ba_dps", cat:"trans", name:"응우라라이 국제공항", en:"Ngurah Rai International Airport", lat:-8.7482, lng:115.1675, area:"꾸따",
    desc:"스미냑 약 30분, 우붓 약 1시간 반.", tip:"차 막힘이 심해 여유 있게." },
];
export const BALI_SAMPLE = [
  { stops:["ba_dps","ba_mulia"], note:"도착 → 리조트에서 휴식" },
  { stops:["ba_sisterfields","ba_seminyak","ba_potato","ba_tanahlot"], note:"스미냑 → 비치클럽 → 따나롯 선셋" },
  { stops:["ba_monkey","ba_ubud","ba_bebek","ba_campuhan"], note:"우붓 데이" },
  { stops:["ba_tegallalang","ba_tirta","ba_ulundanu"], note:"논·사원 투어 (기사 포함 차량 대절 추천)" },
  { stops:["ba_kelingking"], note:"누사 페니다 당일 투어" },
  { stops:["ba_uluwatu","ba_jimbaran"], note:"울루와뚜 께짝 댄스 → 짐바란 씨푸드" },
];

// ---------- 파리 ----------
export const PARIS_PLACES = [
  { id:"pa_eiffel", cat:"sight", name:"에펠탑", en:"Eiffel Tower", lat:48.8584, lng:2.2945, area:"7구",
    desc:"정시마다 5분간 반짝이는 조명 쇼.", tip:"전망대는 공식 사이트에서 미리 예매." },
  { id:"pa_trocadero", cat:"view", name:"트로카데로 광장", en:"Trocadéro Gardens", lat:48.8616, lng:2.2893, area:"16구",
    desc:"에펠탑 정면 최고의 사진 스폿.", tip:"아침 일찍 가면 한산해요." },
  { id:"pa_seine", cat:"trans", name:"센강 유람선 (바토 무슈)", en:"Bateaux Mouches", lat:48.8640, lng:2.3060, area:"8구",
    desc:"해 질 녘 센강 크루즈.", tip:"디너 크루즈도 있어요." },
  { id:"pa_louvre", cat:"sight", name:"루브르 박물관", en:"Louvre Museum", lat:48.8606, lng:2.3376, area:"1구",
    desc:"모나리자·밀로의 비너스.", tip:"시간 지정 예약 필수. 화요일 휴관." },
  { id:"pa_orsay", cat:"sight", name:"오르세 미술관", en:"Musée d'Orsay", lat:48.8600, lng:2.3266, area:"7구",
    desc:"인상파 명작과 거대한 시계창.", tip:"월요일 휴관." },
  { id:"pa_notre", cat:"sight", name:"노트르담 대성당", en:"Notre-Dame de Paris", lat:48.8530, lng:2.3499, area:"시테섬",
    desc:"복원을 마치고 다시 문을 연 고딕 성당.", tip:"" },
  { id:"pa_shakespeare", cat:"shop", name:"셰익스피어 앤 컴퍼니", en:"Shakespeare and Company", lat:48.8526, lng:2.3471, area:"5구",
    desc:"영화 '비포 선셋'의 그 서점.", tip:"" },
  { id:"pa_luxembourg", cat:"nature", name:"뤽상부르 공원", en:"Jardin du Luxembourg", lat:48.8462, lng:2.3372, area:"6구",
    desc:"초록 의자에 앉아 쉬어가는 정원.", tip:"" },
  { id:"pa_vosges", cat:"sight", name:"보주 광장 (마레)", en:"Place des Vosges", lat:48.8556, lng:2.3655, area:"마레",
    desc:"파리에서 가장 오래된 광장. 마레 골목 산책의 시작.", tip:"" },
  { id:"pa_sacre", cat:"view", name:"사크레쾨르 대성당 (몽마르트)", en:"Sacré-Cœur", lat:48.8867, lng:2.3431, area:"몽마르트",
    desc:"파리 전경이 내려다보이는 언덕 위 성당.", tip:"근처 '사랑해 벽'에서 커플 사진." },
  { id:"pa_arc", cat:"view", name:"개선문", en:"Arc de Triomphe", lat:48.8738, lng:2.2950, area:"샹젤리제",
    desc:"옥상 전망대에서 보는 방사형 거리.", tip:"" },
  { id:"pa_champs", cat:"shop", name:"샹젤리제 거리", en:"Avenue des Champs-Élysées", lat:48.8698, lng:2.3078, area:"8구",
    desc:"파리의 대표 쇼핑 거리.", tip:"" },
  { id:"pa_galeries", cat:"shop", name:"갤러리 라파예트", en:"Galeries Lafayette Haussmann", lat:48.8735, lng:2.3320, area:"9구",
    desc:"스테인드글라스 돔 백화점. 무료 옥상 전망.", tip:"면세(택스 리펀) 서류 챙기기." },
  { id:"pa_versailles", cat:"sight", name:"베르사유 궁전", en:"Palace of Versailles", lat:48.8049, lng:2.1204, area:"근교 (RER C 40분)",
    desc:"거울의 방과 거대한 정원.", tip:"월요일 휴관. 하루 일정으로." },
  { id:"pa_angelina", cat:"cafe", name:"안젤리나", en:"Angelina Rivoli", lat:48.8650, lng:2.3284, area:"1구",
    desc:"진한 핫초콜릿과 몽블랑.", tip:"" },
  { id:"pa_flore", cat:"cafe", name:"카페 드 플로르", en:"Café de Flore", lat:48.8541, lng:2.3326, area:"생제르맹",
    desc:"문인들의 단골 카페.", tip:"" },
  { id:"pa_chartier", cat:"food", name:"부이용 샤르티에", en:"Bouillon Chartier", lat:48.8720, lng:2.3434, area:"9구",
    desc:"1896년부터 이어진 가성비 프렌치 식당.", tip:"줄이 길어요. 오픈 시간에 맞춰 가기." },
  { id:"pa_perchoir", cat:"bar", name:"르 페르슈아르", en:"Le Perchoir", lat:48.8653, lng:2.3812, area:"11구",
    desc:"파리 지붕 위 루프탑 바.", tip:"" },
  { id:"pa_plaza", cat:"hotel", name:"플라자 아테네", en:"Hôtel Plaza Athénée", lat:48.8661, lng:2.3044, area:"8구",
    desc:"빨간 차양의 에펠 뷰 호텔.", tip:"" },
  { id:"pa_cdg", cat:"trans", name:"샤를 드골 공항", en:"Charles de Gaulle Airport", lat:49.0097, lng:2.5479, area:"근교",
    desc:"시내까지 RER B 약 40분, 택시 정액제.", tip:"" },
];
export const PARIS_SAMPLE = [
  { stops:["pa_cdg","pa_plaza","pa_trocadero","pa_eiffel","pa_seine"], note:"도착 → 에펠탑 → 센강 야경 크루즈" },
  { stops:["pa_louvre","pa_angelina","pa_orsay","pa_flore"], note:"미술관 데이 (루브르는 시간 예약)" },
  { stops:["pa_notre","pa_shakespeare","pa_luxembourg","pa_vosges","pa_perchoir"], note:"시테섬 → 생제르맹 → 마레 → 루프탑" },
  { stops:["pa_sacre","pa_galeries","pa_chartier","pa_arc","pa_champs"], note:"몽마르트 → 쇼핑 → 개선문 야경" },
  { stops:["pa_versailles"], note:"베르사유 하루" },
];

// ---------- 도쿄 ----------
export const TOKYO_PLACES = [
  { id:"tk_sensoji", cat:"sight", name:"센소지 (아사쿠사)", en:"Sensō-ji", lat:35.7148, lng:139.7967, area:"아사쿠사",
    desc:"도쿄에서 가장 오래된 절. 나카미세 거리 간식.", tip:"기모노 대여하고 사진 찍기 좋아요." },
  { id:"tk_skytree", cat:"view", name:"도쿄 스카이트리", en:"Tokyo Skytree", lat:35.7101, lng:139.8107, area:"오시아게",
    desc:"634m 전망대에서 보는 도쿄 야경.", tip:"" },
  { id:"tk_tsukiji", cat:"food", name:"츠키지 장외시장", en:"Tsukiji Outer Market", lat:35.6655, lng:139.7707, area:"츠키지",
    desc:"아침 스시·계란말이·해산물 꼬치.", tip:"오전에 가야 문 연 가게가 많아요." },
  { id:"tk_meiji", cat:"sight", name:"메이지 신궁", en:"Meiji Jingu", lat:35.6764, lng:139.6993, area:"하라주쿠",
    desc:"도심 속 거대한 숲의 신사.", tip:"운이 좋으면 전통 혼례 행렬을 볼 수 있어요." },
  { id:"tk_takeshita", cat:"shop", name:"다케시타 거리", en:"Takeshita Street", lat:35.6716, lng:139.7031, area:"하라주쿠",
    desc:"크레페와 개성 넘치는 가게들.", tip:"" },
  { id:"tk_omotesando", cat:"shop", name:"오모테산도", en:"Omotesando Hills", lat:35.6673, lng:139.7087, area:"오모테산도",
    desc:"느티나무 가로수길과 명품 건축.", tip:"" },
  { id:"tk_shibuya", cat:"sight", name:"시부야 스크램블 교차로", en:"Shibuya Crossing", lat:35.6595, lng:139.7005, area:"시부야",
    desc:"세계에서 가장 붐비는 교차로.", tip:"" },
  { id:"tk_shibuyasky", cat:"view", name:"시부야 스카이", en:"Shibuya Sky", lat:35.6585, lng:139.7024, area:"시부야",
    desc:"옥상 오픈 전망대. 선셋 명소.", tip:"선셋 시간대는 일찍 매진돼요." },
  { id:"tk_teamlab", cat:"sight", name:"팀랩 플래닛", en:"teamLab Planets", lat:35.6491, lng:139.7898, area:"도요스",
    desc:"물 위를 걷는 몰입형 디지털 아트.", tip:"시간 지정 예약. 반바지 추천(물에 들어가요)." },
  { id:"tk_odaiba", cat:"view", name:"오다이바 해변공원", en:"Odaiba Seaside Park", lat:35.6300, lng:139.7750, area:"오다이바",
    desc:"레인보우 브리지 야경.", tip:"" },
  { id:"tk_tower", cat:"view", name:"도쿄 타워", en:"Tokyo Tower", lat:35.6586, lng:139.7454, area:"시바",
    desc:"주황빛 조명의 클래식 야경.", tip:"시바 공원 쪽에서 보는 모습이 예뻐요." },
  { id:"tk_gyoen", cat:"nature", name:"신주쿠 교엔", en:"Shinjuku Gyoen", lat:35.6852, lng:139.7101, area:"신주쿠",
    desc:"벚꽃·단풍 명소 정원.", tip:"월요일 휴원." },
  { id:"tk_ginza", cat:"shop", name:"긴자 식스", en:"Ginza Six", lat:35.6697, lng:139.7640, area:"긴자",
    desc:"긴자 대표 쇼핑몰과 무료 옥상 정원.", tip:"" },
  { id:"tk_goldengai", cat:"bar", name:"골든가이", en:"Golden Gai", lat:35.6938, lng:139.7046, area:"신주쿠",
    desc:"좁은 골목의 작은 바 200여 곳.", tip:"자릿세(차지)가 있는 곳이 많아요." },
  { id:"tk_bluebottle", cat:"cafe", name:"블루보틀 기요스미시라카와", en:"Blue Bottle Coffee Kiyosumi", lat:35.6806, lng:139.7963, area:"기요스미",
    desc:"블루보틀 일본 1호점.", tip:"" },
  { id:"tk_parkhyatt", cat:"hotel", name:"파크 하얏트 도쿄", en:"Park Hyatt Tokyo", lat:35.6856, lng:139.6907, area:"신주쿠",
    desc:"영화 '사랑도 통역이 되나요'의 뉴욕 바.", tip:"" },
  { id:"tk_hnd", cat:"trans", name:"하네다 공항", en:"Haneda Airport", lat:35.5494, lng:139.7798, area:"오타구",
    desc:"시내까지 전철·리무진 버스 약 30분.", tip:"" },
];
export const TOKYO_SAMPLE = [
  { stops:["tk_hnd","tk_parkhyatt","tk_goldengai"], note:"도착 → 신주쿠 밤" },
  { stops:["tk_tsukiji","tk_sensoji","tk_skytree"], note:"츠키지 아침 → 아사쿠사 → 스카이트리 야경" },
  { stops:["tk_meiji","tk_takeshita","tk_omotesando","tk_shibuya","tk_shibuyasky"], note:"하라주쿠 → 오모테산도 → 시부야 선셋" },
  { stops:["tk_bluebottle","tk_teamlab","tk_odaiba","tk_tower"], note:"팀랩 → 오다이바 → 도쿄 타워" },
  { stops:["tk_gyoen","tk_ginza"], note:"정원 산책 → 긴자 쇼핑" },
];

// ---------- 다낭 · 호이안 ----------
export const DANANG_PLACES = [
  { id:"dn_mykhe", cat:"beach", name:"미케 비치", en:"My Khe Beach", lat:16.0600, lng:108.2470, area:"다낭",
    desc:"길게 뻗은 도심 해변.", tip:"" },
  { id:"dn_dragon", cat:"sight", name:"용다리", en:"Dragon Bridge", lat:16.0612, lng:108.2272, area:"다낭",
    desc:"주말 밤 9시 불·물 뿜는 쇼.", tip:"토·일 밤 9시." },
  { id:"dn_hanmarket", cat:"shop", name:"한 시장", en:"Han Market", lat:16.0682, lng:108.2240, area:"다낭",
    desc:"기념품·커피·아오자이 맞춤.", tip:"흥정 필수." },
  { id:"dn_church", cat:"sight", name:"다낭 대성당 (핑크 성당)", en:"Da Nang Cathedral", lat:16.0668, lng:108.2232, area:"다낭",
    desc:"분홍빛 성당 앞 커플 사진.", tip:"" },
  { id:"dn_marble", cat:"nature", name:"오행산 (마블 마운틴)", en:"Marble Mountains", lat:16.0040, lng:108.2630, area:"응우한선",
    desc:"동굴 사원과 전망대가 있는 대리석 산.", tip:"엘리베이터로 올라가면 편해요." },
  { id:"dn_linhung", cat:"view", name:"영흥사 (선짜반도)", en:"Linh Ung Pagoda", lat:16.1003, lng:108.2779, area:"선짜반도",
    desc:"67m 해수관음상과 다낭 해안 전경.", tip:"" },
  { id:"dn_bana", cat:"sight", name:"바나힐 (골든 브리지)", en:"Ba Na Hills", lat:15.9950, lng:107.9960, area:"근교 (차로 1시간)",
    desc:"거대한 손이 받친 골든 브리지와 케이블카.", tip:"구름 없는 오전 추천." },
  { id:"dn_hoian", cat:"sight", name:"호이안 구시가지", en:"Hoi An Ancient Town", lat:15.8770, lng:108.3260, area:"호이안",
    desc:"등불이 밝혀진 옛 무역항 거리.", tip:"저녁에 소원 배 띄우기." },
  { id:"dn_hoianmarket", cat:"shop", name:"호이안 야시장", en:"Hoi An Night Market", lat:15.8760, lng:108.3290, area:"호이안",
    desc:"등불 가게와 길거리 음식.", tip:"" },
  { id:"dn_banhmi", cat:"food", name:"반미 프엉", en:"Bánh Mì Phượng", lat:15.8775, lng:108.3315, area:"호이안",
    desc:"줄 서서 먹는 호이안 반미.", tip:"" },
  { id:"dn_anbang", cat:"beach", name:"안방 비치", en:"An Bang Beach", lat:15.9133, lng:108.3400, area:"호이안",
    desc:"한적한 비치 카페와 선베드.", tip:"" },
  { id:"dn_myson", cat:"sight", name:"미선 유적지", en:"Mỹ Sơn", lat:15.7640, lng:108.1240, area:"근교 (차로 1시간 반)",
    desc:"참파 왕국의 힌두 사원 유적.", tip:"더위 전 새벽 투어 추천." },
  { id:"dn_sky36", cat:"bar", name:"스카이36", en:"Sky36", lat:16.0716, lng:108.2236, area:"다낭",
    desc:"노보텔 꼭대기 루프탑 바.", tip:"드레스 코드 있어요 (슬리퍼 X)." },
  { id:"dn_intercon", cat:"hotel", name:"인터컨티넨탈 썬 페닌슐라", en:"InterContinental Danang Sun Peninsula Resort", lat:16.1177, lng:108.3086, area:"선짜반도",
    desc:"정글 언덕 위 허니문 리조트.", tip:"" },
  { id:"dn_dad", cat:"trans", name:"다낭 국제공항", en:"Da Nang International Airport", lat:16.0439, lng:108.1994, area:"다낭",
    desc:"시내 약 15분, 호이안 약 45분.", tip:"" },
];
export const DANANG_SAMPLE = [
  { stops:["dn_dad","dn_intercon","dn_linhung","dn_sky36"], note:"도착 → 선짜반도 → 루프탑 야경" },
  { stops:["dn_bana"], note:"바나힐 하루" },
  { stops:["dn_marble","dn_mykhe","dn_church","dn_hanmarket","dn_dragon"], note:"오행산 → 해변 → 시내 (주말 밤 용다리 쇼)" },
  { stops:["dn_anbang","dn_banhmi","dn_hoian","dn_hoianmarket"], note:"호이안 등불 밤" },
  { stops:["dn_myson"], note:"미선 유적 새벽 투어" },
];
